target("outcpp")
  set_toolset("cxxflags", "/permissive-")
  set_targetdir("$(buildir)/vc/$(host)/$(mode)/$(arch)")
  set_objectdir("$(buildir)/vc/.objs")
  set_dependir("$(buildir)/vc/.deps")
  set_kind("binary")
  add_packages("boost")
  add_includedirs("..", {public = true})
  add_includedirs(".")
  add_files("../rt/**.cpp", "**.cpp")

target("outcpp-gcc")
  set_toolchains("gcc")
  set_targetdir("$(buildir)/gcc/$(host)/$(mode)/$(arch)")
  set_objectdir("$(buildir)/gcc/.objs")
  set_dependir("$(buildir)/gcc/.deps")
  set_kind("binary")
  add_packages("boost")
  add_includedirs("..", {public = true})
  add_includedirs(".")
  add_files("../rt/**.cpp", "**.cpp")

target("outcpp-clang")
  set_toolchains("clang")
  set_targetdir("$(buildir)/clang/$(host)/$(mode)/$(arch)")
  set_objectdir("$(buildir)/clang/.objs")
  set_dependir("$(buildir)/clang/.deps")
  set_kind("binary")
  add_packages("boost")
  add_includedirs("..", {public = true})
  add_includedirs(".")
  add_files("../rt/**.cpp", "**.cpp")