#pragma once

#include "ILGenerator.h"

#include <System.Private.CoreLib/System/Array-dep.h>
#include <System.Private.CoreLib/System/Boolean-dep.h>
#include <System.Private.CoreLib/System/Byte-dep.h>
#include <System.Private.CoreLib/System/Diagnostics/SymbolStore/ISymbolDocumentWriter.h>
#include <System.Private.CoreLib/System/Double-dep.h>
#include <System.Private.CoreLib/System/Int16-dep.h>
#include <System.Private.CoreLib/System/Int32-dep.h>
#include <System.Private.CoreLib/System/Int64-dep.h>
#include <System.Private.CoreLib/System/Reflection/CallingConventions.h>
#include <System.Private.CoreLib/System/Reflection/ConstructorInfo-dep.h>
#include <System.Private.CoreLib/System/Reflection/Emit/__ExceptionInfo-dep.h>
#include <System.Private.CoreLib/System/Reflection/Emit/__FixupData-dep.h>
#include <System.Private.CoreLib/System/Reflection/Emit/Label-dep.h>
#include <System.Private.CoreLib/System/Reflection/Emit/LineNumberInfo-dep.h>
#include <System.Private.CoreLib/System/Reflection/Emit/LocalBuilder-dep.h>
#include <System.Private.CoreLib/System/Reflection/Emit/OpCode-dep.h>
#include <System.Private.CoreLib/System/Reflection/Emit/ScopeTree-dep.h>
#include <System.Private.CoreLib/System/Reflection/Emit/SignatureHelper-dep.h>
#include <System.Private.CoreLib/System/Reflection/FieldInfo-dep.h>
#include <System.Private.CoreLib/System/Reflection/MethodBase-dep.h>
#include <System.Private.CoreLib/System/Reflection/MethodInfo-dep.h>
#include <System.Private.CoreLib/System/Runtime/InteropServices/CallingConvention.h>
#include <System.Private.CoreLib/System/SByte-dep.h>
#include <System.Private.CoreLib/System/Single-dep.h>
#include <System.Private.CoreLib/System/String-dep.h>
#include <System.Private.CoreLib/System/Type-dep.h>
