#pragma once

#include <cstdint>

namespace System::Private::CoreLib::System {
enum class ExceptionResource : int32_t {
  ArgumentOutOfRange_Index = 0,
  ArgumentOutOfRange_IndexCount = 1,
  ArgumentOutOfRange_IndexCountBuffer = 2,
  ArgumentOutOfRange_Count = 3,
  ArgumentOutOfRange_Year = 4,
  Arg_ArrayPlusOffTooSmall = 5,
  NotSupported_ReadOnlyCollection = 6,
  Arg_RankMultiDimNotSupported = 7,
  Arg_NonZeroLowerBound = 8,
  ArgumentOutOfRange_GetCharCountOverflow = 9,
  ArgumentOutOfRange_ListInsert = 10,
  ArgumentOutOfRange_NeedNonNegNum = 11,
  ArgumentOutOfRange_SmallCapacity = 12,
  Argument_InvalidOffLen = 13,
  Argument_CannotExtractScalar = 14,
  ArgumentOutOfRange_BiggerThanCollection = 15,
  Serialization_MissingKeys = 16,
  Serialization_NullKey = 17,
  NotSupported_KeyCollectionSet = 18,
  NotSupported_ValueCollectionSet = 19,
  InvalidOperation_NullArray = 20,
  TaskT_TransitionToFinal_AlreadyCompleted = 21,
  TaskCompletionSourceT_TrySetException_NullException = 22,
  TaskCompletionSourceT_TrySetException_NoExceptions = 23,
  NotSupported_StringComparison = 24,
  ConcurrentCollection_SyncRoot_NotSupported = 25,
  Task_MultiTaskContinuation_NullTask = 26,
  InvalidOperation_WrongAsyncResultOrEndCalledMultiple = 27,
  Task_MultiTaskContinuation_EmptyTaskList = 28,
  Task_Start_TaskCompleted = 29,
  Task_Start_Promise = 30,
  Task_Start_ContinuationTask = 31,
  Task_Start_AlreadyStarted = 32,
  Task_RunSynchronously_Continuation = 33,
  Task_RunSynchronously_Promise = 34,
  Task_RunSynchronously_TaskCompleted = 35,
  Task_RunSynchronously_AlreadyStarted = 36,
  AsyncMethodBuilder_InstanceNotInitialized = 37,
  Task_ContinueWith_ESandLR = 38,
  Task_ContinueWith_NotOnAnything = 39,
  Task_Delay_InvalidDelay = 40,
  Task_Delay_InvalidMillisecondsDelay = 41,
  Task_Dispose_NotCompleted = 42,
  Task_ThrowIfDisposed = 43,
  Task_WaitMulti_NullTask = 44,
  ArgumentException_OtherNotArrayOfCorrectLength = 45,
  ArgumentNull_Array = 46,
  ArgumentNull_SafeHandle = 47,
  ArgumentOutOfRange_EndIndexStartIndex = 48,
  ArgumentOutOfRange_Enum = 49,
  ArgumentOutOfRange_HugeArrayNotSupported = 50,
  Argument_AddingDuplicate = 51,
  Argument_InvalidArgumentForComparison = 52,
  Arg_LowerBoundsMustMatch = 53,
  Arg_MustBeType = 54,
  Arg_Need1DArray = 55,
  Arg_Need2DArray = 56,
  Arg_Need3DArray = 57,
  Arg_NeedAtLeast1Rank = 58,
  Arg_RankIndices = 59,
  Arg_RanksAndBounds = 60,
  InvalidOperation_IComparerFailed = 61,
  NotSupported_FixedSizeCollection = 62,
  Rank_MultiDimNotSupported = 63,
  Arg_TypeNotSupported = 64,
  Argument_SpansMustHaveSameLength = 65,
  Argument_InvalidFlag = 66,
};
} // namespace System::Private::CoreLib::System
