#pragma once

#include <cstdint>

namespace System::Private::CoreLib::System {
enum class ExceptionResource : int32_t {
  ArgumentOutOfRange_Index = 0,
  ArgumentOutOfRange_IndexCount = 1,
  ArgumentOutOfRange_IndexCountBuffer = 2,
  ArgumentOutOfRange_Count = 3,
  ArgumentOutOfRange_Year = 4,
  Arg_ArrayPlusOffTooSmall = 5,
  NotSupported_ReadOnlyCollection = 6,
  Arg_RankMultiDimNotSupported = 7,
  Arg_NonZeroLowerBound = 8,
  ArgumentOutOfRange_ListInsert = 9,
  ArgumentOutOfRange_NeedNonNegNum = 10,
  ArgumentOutOfRange_SmallCapacity = 11,
  Argument_InvalidOffLen = 12,
  Argument_CannotExtractScalar = 13,
  ArgumentOutOfRange_BiggerThanCollection = 14,
  Serialization_MissingKeys = 15,
  Serialization_NullKey = 16,
  NotSupported_KeyCollectionSet = 17,
  NotSupported_ValueCollectionSet = 18,
  InvalidOperation_NullArray = 19,
  TaskT_TransitionToFinal_AlreadyCompleted = 20,
  TaskCompletionSourceT_TrySetException_NullException = 21,
  TaskCompletionSourceT_TrySetException_NoExceptions = 22,
  NotSupported_StringComparison = 23,
  ConcurrentCollection_SyncRoot_NotSupported = 24,
  Task_MultiTaskContinuation_NullTask = 25,
  InvalidOperation_WrongAsyncResultOrEndCalledMultiple = 26,
  Task_MultiTaskContinuation_EmptyTaskList = 27,
  Task_Start_TaskCompleted = 28,
  Task_Start_Promise = 29,
  Task_Start_ContinuationTask = 30,
  Task_Start_AlreadyStarted = 31,
  Task_RunSynchronously_Continuation = 32,
  Task_RunSynchronously_Promise = 33,
  Task_RunSynchronously_TaskCompleted = 34,
  Task_RunSynchronously_AlreadyStarted = 35,
  AsyncMethodBuilder_InstanceNotInitialized = 36,
  Task_ContinueWith_ESandLR = 37,
  Task_ContinueWith_NotOnAnything = 38,
  Task_Delay_InvalidDelay = 39,
  Task_Delay_InvalidMillisecondsDelay = 40,
  Task_Dispose_NotCompleted = 41,
  Task_ThrowIfDisposed = 42,
  Task_WaitMulti_NullTask = 43,
  ArgumentException_OtherNotArrayOfCorrectLength = 44,
  ArgumentNull_Array = 45,
  ArgumentNull_SafeHandle = 46,
  ArgumentOutOfRange_EndIndexStartIndex = 47,
  ArgumentOutOfRange_Enum = 48,
  ArgumentOutOfRange_HugeArrayNotSupported = 49,
  Argument_AddingDuplicate = 50,
  Argument_InvalidArgumentForComparison = 51,
  Arg_LowerBoundsMustMatch = 52,
  Arg_MustBeType = 53,
  Arg_Need1DArray = 54,
  Arg_Need2DArray = 55,
  Arg_Need3DArray = 56,
  Arg_NeedAtLeast1Rank = 57,
  Arg_RankIndices = 58,
  Arg_RanksAndBounds = 59,
  InvalidOperation_IComparerFailed = 60,
  NotSupported_FixedSizeCollection = 61,
  Rank_MultiDimNotSupported = 62,
  Arg_TypeNotSupported = 63,
  Argument_SpansMustHaveSameLength = 64,
  Argument_InvalidFlag = 65,
};
} // namespace System::Private::CoreLib::System
